"""añadido cellphone

Revision ID: 19e969a288e4
Revises: 1460f3dae2eb
Create Date: 2026-03-19 22:08:09.880814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e969a288e4'
down_revision: Union[str, Sequence[str], None] = '1460f3dae2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('housephone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'housephone')
    # ### end Alembic commands ###
